Repository CodersCrew/coderscamp-app, pull requests merged in 2021-06, with the labels that each got.

#19 added spinner and validation to sign in page
  api/package-lock.json
  frontend/src/pages/Common/LogIn/LogIn.tsx
  package-lock.json
Labels: bug

#21 removed unnecessary request when adding new section
  frontend/src/api/Section.api.ts
Labels: bug

#35 added endpoint for adding users to a team
  api/Src/Controllers/TeamController.ts
  api/Src/Repositories/Repository.ts
  api/Src/Repositories/TeamRepository.ts
  api/Src/Routes/TeamRoutes.ts
  api/Src/Services/TeamService.ts
  api/swagger.yml
Labels: enhancement

#31 Fit content
  frontend/src/components/DetailPage/DetailPage.tsx
  frontend/src/components/PageContainer/PageContainer.module.css
  frontend/src/components/PageContainer/PageContainer.tsx
  frontend/src/components/PageContainer/index.ts
  frontend/src/components/ReusableTable/ReusableTable.tsx
  frontend/src/components/TableContainer/TableContainer.module.css
  frontend/src/components/TableContainer/TableContainer.tsx
  frontend/src/components/TableContainer/index.ts
  frontend/src/pages/Admin/Course/CourseDetails.tsx
  frontend/src/pages/Admin/CourseList/CourseList.module.css
  frontend/src/pages/Admin/CourseList/CourseList.tsx
  frontend/src/pages/Admin/CourseList/CourseListElement.tsx
  frontend/src/pages/Admin/ManageSections/ManageSections.module.css
  frontend/src/pages/Admin/ManageSections/ManageSections.tsx
  frontend/src/pages/Admin/ManageSheet/ManageSheet.tsx
  frontend/src/pages/Admin/ManageSheets/ManageSheets.module.css
  frontend/src/pages/Admin/ManageSheets/ManageSheets.tsx
  frontend/src/pages/Admin/ManageTeam/ManageTeam.module.css
  frontend/src/pages/Admin/ManageTeam/ManageTeam.tsx
  frontend/src/pages/Admin/ManageTeams/ManageTeams.module.css
  frontend/src/pages/Admin/ManageTeams/ManageTeams.tsx
  frontend/src/pages/Admin/ManageUser/ManageUser.tsx
  frontend/src/pages/Admin/ManageUsers/ManageUsers.module.css
  frontend/src/pages/Admin/ManageUsers/ManageUsers.tsx
  frontend/src/pages/Admin/ReferenceProjects/ReferenceProjects.tsx
  frontend/src/pages/Admin/SectionView/SectionView.module.css
  frontend/src/pages/Admin/SectionView/SectionView.tsx
  frontend/src/pages/Admin/TeamProjects/TeamProjects.tsx
  frontend/src/pages/Common/HomePage/HomePage.tsx
  frontend/src/pages/Common/HomePage/__snapshots__/HomePage.test.tsx.snap
  frontend/src/pages/Common/MyProfile/MyProfile.module.css
  frontend/src/pages/Common/MyProfile/MyProfile.tsx
Labels: Layout

#39 Adding multiple users to a team functionality
  frontend/src/api/Team.api.ts
  frontend/src/components/FindModal/FindModal.module.css
  frontend/src/components/FindModal/FindModal.tsx
  frontend/src/hooks/useQuery/useTeam.ts
  frontend/src/pages/Admin/ManageTeam/ManageTeam.tsx
  frontend/src/pages/Common/LogIn/LogIn.tsx
  frontend/src/pages/Common/Registration/Registration.tsx
Labels: enhancement
